/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vhscs3.doormanagerv6;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JComponent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author irad_Allen
 */
public class MainWindow extends javax.swing.JFrame {
    
    private HashMap<String, Door>       doors;             //Collection of doors, door name is the key
    private HashMap<String, Schedule>   schedules;         //Collection of schedules, schedule name is the key
    private HashMap<Integer, Badge>     badges;            //Collection of BADGES, employeeID is the key
    private JComponent[] scheduleComponents;                 //Form elements for schedule

    public MainWindow() {
        
        //DataFactory df = new DataFactory();
        //writeModel(df.getModel());

        DoorManagerModel model = readModel();
        doors = model.doors;
        schedules = model.schedules;
        badges = model.badges;
        
        // Test to make sure data is written and retrieved correctly
        for (String key : doors.keySet()) {
            System.out.println(doors.get(key));
        }
        
        initComponents();
        
        scheduleComponents = new JComponent[10];
        buildScheduleGroup();
        buildDoorGroup();
        
        setGroupEnabled(false, scheduleComponents);
        DoorGroupEnabled(false);
        
        buildschedulestables();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWindow_tabbedPane = new javax.swing.JTabbedPane();
        dashBoard_panel = new javax.swing.JPanel();
        doors_panel = new javax.swing.JPanel();
        doors_scrollpane_display = new javax.swing.JScrollPane();
        doors_table_doors = new javax.swing.JTable();
        doors_panel_CRUD = new javax.swing.JPanel();
        doors_button_new = new javax.swing.JButton();
        doors_button_edit = new javax.swing.JButton();
        doors_button_delete = new javax.swing.JButton();
        doors_button_save = new javax.swing.JButton();
        doors_panel_editor = new javax.swing.JPanel();
        doors_label_doorName = new javax.swing.JLabel();
        doors_textfield_doorname = new javax.swing.JTextField();
        doors_label_status = new javax.swing.JLabel();
        doors_label_statusIndicatior = new javax.swing.JLabel();
        doors_label_location = new javax.swing.JLabel();
        doors_button_location = new javax.swing.JButton();
        doors_label_building = new javax.swing.JLabel();
        doors_radioButton_1 = new javax.swing.JRadioButton();
        doors_radioButton_2 = new javax.swing.JRadioButton();
        doors_radioButton_3 = new javax.swing.JRadioButton();
        doors_label_schedules = new javax.swing.JLabel();
        doors_comboBox_1 = new javax.swing.JComboBox<>();
        doors_comboBox_2 = new javax.swing.JComboBox<>();
        doors_comboBox_3 = new javax.swing.JComboBox<>();
        doors_comboBox_4 = new javax.swing.JComboBox<>();
        doors_comboBox_5 = new javax.swing.JComboBox<>();
        doors_comboBox_6 = new javax.swing.JComboBox<>();
        doors_comboBox_7 = new javax.swing.JComboBox<>();
        doors_label_monday = new javax.swing.JLabel();
        doors_label_tuesday = new javax.swing.JLabel();
        doors_label_wednesday = new javax.swing.JLabel();
        doors_label_thursday = new javax.swing.JLabel();
        doors_label_friday = new javax.swing.JLabel();
        doors_label_saturday = new javax.swing.JLabel();
        doors_label_sunday = new javax.swing.JLabel();
        doors_label_logs = new javax.swing.JLabel();
        doors_scrollpane_logs = new javax.swing.JScrollPane();
        doors_table_logs = new javax.swing.JTable();
        schedules_panel = new javax.swing.JPanel();
        schedules_ScrollPane_display = new javax.swing.JScrollPane();
        schedules_table = new javax.swing.JTable();
        schedules_CRUD_bottons = new javax.swing.JPanel();
        schedules_botton_edit = new javax.swing.JButton();
        schedules_botton_add = new javax.swing.JButton();
        schedules_botton_delete = new javax.swing.JButton();
        schedules_botton_save = new javax.swing.JButton();
        schedules_panel_editor = new javax.swing.JPanel();
        schedules_label_name = new javax.swing.JLabel();
        schedules_textfield_name = new javax.swing.JTextField();
        schedules_textfield_description = new javax.swing.JTextField();
        schedules_label_description = new javax.swing.JLabel();
        schedules_button_color = new javax.swing.JButton();
        schedules_label_color = new javax.swing.JLabel();
        schedules_label_colorindicator = new javax.swing.JLabel();
        schedules_label_times = new javax.swing.JLabel();
        schedules_button_addtime = new javax.swing.JButton();
        schedules_button_edittime = new javax.swing.JButton();
        schedules_button_deletetime = new javax.swing.JButton();
        schedules_scrollpane_times = new javax.swing.JScrollPane();
        schedules_table_times = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dashBoard_panelLayout = new javax.swing.GroupLayout(dashBoard_panel);
        dashBoard_panel.setLayout(dashBoard_panelLayout);
        dashBoard_panelLayout.setHorizontalGroup(
            dashBoard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1144, Short.MAX_VALUE)
        );
        dashBoard_panelLayout.setVerticalGroup(
            dashBoard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );

        mainWindow_tabbedPane.addTab("Dashboard", dashBoard_panel);

        doors_table_doors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Status", "Color", "Schedule", "Building"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doors_table_doors.setColumnSelectionAllowed(true);
        doors_scrollpane_display.setViewportView(doors_table_doors);
        doors_table_doors.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        doors_button_new.setText("New");

        doors_button_edit.setText("Edit");

        doors_button_delete.setText("Delete");

        doors_button_save.setText("Save");

        javax.swing.GroupLayout doors_panel_CRUDLayout = new javax.swing.GroupLayout(doors_panel_CRUD);
        doors_panel_CRUD.setLayout(doors_panel_CRUDLayout);
        doors_panel_CRUDLayout.setHorizontalGroup(
            doors_panel_CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doors_panel_CRUDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(doors_button_new)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doors_button_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doors_button_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doors_button_save))
        );
        doors_panel_CRUDLayout.setVerticalGroup(
            doors_panel_CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doors_panel_CRUDLayout.createSequentialGroup()
                .addGroup(doors_panel_CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doors_button_new)
                    .addComponent(doors_button_edit)
                    .addComponent(doors_button_delete)
                    .addComponent(doors_button_save))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        doors_label_doorName.setText("Door Name");

        doors_label_status.setText("Status");

        doors_label_statusIndicatior.setText("OPEN");

        doors_label_location.setText("Location");

        doors_button_location.setText("Set Location");

        doors_label_building.setText("Building");

        doors_radioButton_1.setText("1");

        doors_radioButton_2.setText("2");

        doors_radioButton_3.setText("3");

        doors_label_schedules.setText("Schedules");

        doors_comboBox_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "Rgular", "EODPIT", "LateStart", "InteriorDoors", "HalfDay", "RobotRoom", "specialEvents " }));
        doors_comboBox_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doors_comboBox_1ActionPerformed(evt);
            }
        });

        doors_comboBox_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "Rgular", "EODPIT", "LateStart", "InteriorDoors", "HalfDay", "RobotRoom", "specialEvents " }));
        doors_comboBox_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doors_comboBox_2ActionPerformed(evt);
            }
        });

        doors_comboBox_3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "Rgular", "EODPIT", "LateStart", "InteriorDoors", "HalfDay", "RobotRoom", "specialEvents " }));
        doors_comboBox_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doors_comboBox_3ActionPerformed(evt);
            }
        });

        doors_comboBox_4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "Rgular", "EODPIT", "LateStart", "InteriorDoors", "HalfDay", "RobotRoom", "specialEvents " }));
        doors_comboBox_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doors_comboBox_4ActionPerformed(evt);
            }
        });

        doors_comboBox_5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "Rgular", "EODPIT", "LateStart", "InteriorDoors", "HalfDay", "RobotRoom", "specialEvents " }));
        doors_comboBox_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doors_comboBox_5ActionPerformed(evt);
            }
        });

        doors_comboBox_6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "Rgular", "EODPIT", "LateStart", "InteriorDoors", "HalfDay", "RobotRoom", "specialEvents " }));
        doors_comboBox_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doors_comboBox_6ActionPerformed(evt);
            }
        });

        doors_comboBox_7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "Rgular", "EODPIT", "LateStart", "InteriorDoors", "HalfDay", "RobotRoom", "specialEvents " }));
        doors_comboBox_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doors_comboBox_7ActionPerformed(evt);
            }
        });

        doors_label_monday.setText("Monday");

        doors_label_tuesday.setText("Tuesday");

        doors_label_wednesday.setText("Wednesday");

        doors_label_thursday.setText("Thursday");

        doors_label_friday.setText("Friday");

        doors_label_saturday.setText("Saturday");

        doors_label_sunday.setText("Sunday");

        doors_label_logs.setText("Logs");

        doors_table_logs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Time Stamp", "Employee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doors_table_logs.setColumnSelectionAllowed(true);
        doors_scrollpane_logs.setViewportView(doors_table_logs);
        doors_table_logs.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout doors_panel_editorLayout = new javax.swing.GroupLayout(doors_panel_editor);
        doors_panel_editor.setLayout(doors_panel_editorLayout);
        doors_panel_editorLayout.setHorizontalGroup(
            doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doors_panel_editorLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(doors_label_logs)
                    .addComponent(doors_label_schedules)
                    .addComponent(doors_label_building)
                    .addComponent(doors_label_location)
                    .addComponent(doors_label_status)
                    .addComponent(doors_label_doorName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doors_textfield_doorname)
                    .addGroup(doors_panel_editorLayout.createSequentialGroup()
                        .addGroup(doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(doors_panel_editorLayout.createSequentialGroup()
                                .addComponent(doors_comboBox_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doors_label_sunday))
                            .addGroup(doors_panel_editorLayout.createSequentialGroup()
                                .addComponent(doors_comboBox_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doors_label_saturday))
                            .addGroup(doors_panel_editorLayout.createSequentialGroup()
                                .addComponent(doors_comboBox_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doors_label_friday))
                            .addGroup(doors_panel_editorLayout.createSequentialGroup()
                                .addComponent(doors_comboBox_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doors_label_thursday))
                            .addGroup(doors_panel_editorLayout.createSequentialGroup()
                                .addComponent(doors_comboBox_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doors_label_tuesday))
                            .addGroup(doors_panel_editorLayout.createSequentialGroup()
                                .addComponent(doors_comboBox_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doors_label_wednesday))
                            .addComponent(doors_label_statusIndicatior)
                            .addComponent(doors_button_location)
                            .addGroup(doors_panel_editorLayout.createSequentialGroup()
                                .addComponent(doors_radioButton_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doors_radioButton_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doors_radioButton_3))
                            .addGroup(doors_panel_editorLayout.createSequentialGroup()
                                .addComponent(doors_comboBox_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doors_label_monday)))
                        .addContainerGap())
                    .addGroup(doors_panel_editorLayout.createSequentialGroup()
                        .addComponent(doors_scrollpane_logs, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 27, Short.MAX_VALUE))))
        );
        doors_panel_editorLayout.setVerticalGroup(
            doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doors_panel_editorLayout.createSequentialGroup()
                .addGroup(doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doors_label_doorName)
                    .addComponent(doors_textfield_doorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doors_label_status)
                    .addComponent(doors_label_statusIndicatior))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doors_label_location)
                    .addComponent(doors_button_location))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doors_label_building)
                    .addComponent(doors_radioButton_1)
                    .addComponent(doors_radioButton_2)
                    .addComponent(doors_radioButton_3))
                .addGap(18, 18, 18)
                .addGroup(doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doors_label_schedules)
                    .addComponent(doors_comboBox_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doors_label_monday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doors_comboBox_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doors_label_tuesday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doors_comboBox_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doors_label_wednesday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doors_comboBox_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doors_label_thursday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doors_comboBox_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doors_label_friday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doors_comboBox_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doors_label_saturday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doors_comboBox_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doors_label_sunday))
                .addGap(18, 18, 18)
                .addGroup(doors_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doors_label_logs)
                    .addComponent(doors_scrollpane_logs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout doors_panelLayout = new javax.swing.GroupLayout(doors_panel);
        doors_panel.setLayout(doors_panelLayout);
        doors_panelLayout.setHorizontalGroup(
            doors_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doors_panelLayout.createSequentialGroup()
                .addComponent(doors_scrollpane_display, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doors_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doors_panel_CRUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doors_panel_editor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        doors_panelLayout.setVerticalGroup(
            doors_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doors_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(doors_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(doors_panelLayout.createSequentialGroup()
                        .addComponent(doors_panel_CRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(doors_panel_editor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(doors_scrollpane_display))
                .addContainerGap())
        );

        mainWindow_tabbedPane.addTab("Doors", doors_panel);

        schedules_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Description", "Color", "Open Times"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        schedules_table.setColumnSelectionAllowed(true);
        schedules_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schedules_tableMouseClicked(evt);
            }
        });
        schedules_ScrollPane_display.setViewportView(schedules_table);
        schedules_table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        schedules_botton_edit.setText("Edit");

        schedules_botton_add.setText("Add");

        schedules_botton_delete.setText("Delete");

        schedules_botton_save.setText("Save");

        javax.swing.GroupLayout schedules_CRUD_bottonsLayout = new javax.swing.GroupLayout(schedules_CRUD_bottons);
        schedules_CRUD_bottons.setLayout(schedules_CRUD_bottonsLayout);
        schedules_CRUD_bottonsLayout.setHorizontalGroup(
            schedules_CRUD_bottonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schedules_CRUD_bottonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(schedules_botton_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(schedules_botton_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(schedules_botton_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(schedules_botton_save))
        );
        schedules_CRUD_bottonsLayout.setVerticalGroup(
            schedules_CRUD_bottonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schedules_CRUD_bottonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(schedules_botton_edit)
                .addComponent(schedules_botton_add)
                .addComponent(schedules_botton_delete)
                .addComponent(schedules_botton_save))
        );

        schedules_label_name.setText("Name");

        schedules_label_description.setText("Description");

        schedules_button_color.setText("Color");
        schedules_button_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedules_button_colorActionPerformed(evt);
            }
        });

        schedules_label_color.setText("Color");

        schedules_label_times.setText("Times");

        schedules_button_addtime.setText("Add Time");

        schedules_button_edittime.setText("Edit Time");

        schedules_button_deletetime.setText("Delete Time");

        schedules_table_times.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Open Time", "Close Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        schedules_table_times.setColumnSelectionAllowed(true);
        schedules_scrollpane_times.setViewportView(schedules_table_times);
        schedules_table_times.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout schedules_panel_editorLayout = new javax.swing.GroupLayout(schedules_panel_editor);
        schedules_panel_editor.setLayout(schedules_panel_editorLayout);
        schedules_panel_editorLayout.setHorizontalGroup(
            schedules_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, schedules_panel_editorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(schedules_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(schedules_label_times)
                    .addComponent(schedules_label_name)
                    .addComponent(schedules_label_description)
                    .addComponent(schedules_label_color))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(schedules_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schedules_scrollpane_times, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(schedules_panel_editorLayout.createSequentialGroup()
                        .addComponent(schedules_button_color)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(schedules_label_colorindicator, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(schedules_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(schedules_textfield_name)
                        .addComponent(schedules_textfield_description, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                    .addGroup(schedules_panel_editorLayout.createSequentialGroup()
                        .addComponent(schedules_button_addtime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(schedules_button_edittime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(schedules_button_deletetime))))
        );
        schedules_panel_editorLayout.setVerticalGroup(
            schedules_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schedules_panel_editorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(schedules_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schedules_label_name)
                    .addComponent(schedules_textfield_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(schedules_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schedules_textfield_description, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schedules_label_description))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(schedules_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(schedules_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(schedules_button_color)
                        .addComponent(schedules_label_color))
                    .addGroup(schedules_panel_editorLayout.createSequentialGroup()
                        .addComponent(schedules_label_colorindicator, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(schedules_panel_editorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schedules_label_times)
                    .addComponent(schedules_button_addtime)
                    .addComponent(schedules_button_edittime)
                    .addComponent(schedules_button_deletetime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(schedules_scrollpane_times, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout schedules_panelLayout = new javax.swing.GroupLayout(schedules_panel);
        schedules_panel.setLayout(schedules_panelLayout);
        schedules_panelLayout.setHorizontalGroup(
            schedules_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schedules_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(schedules_ScrollPane_display, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(schedules_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schedules_CRUD_bottons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(schedules_panel_editor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        schedules_panelLayout.setVerticalGroup(
            schedules_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schedules_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(schedules_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schedules_ScrollPane_display)
                    .addGroup(schedules_panelLayout.createSequentialGroup()
                        .addComponent(schedules_CRUD_bottons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(schedules_panel_editor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        mainWindow_tabbedPane.addTab("Schedules", schedules_panel);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainWindow_tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1144, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainWindow_tabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doors_comboBox_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doors_comboBox_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doors_comboBox_1ActionPerformed

    private void doors_comboBox_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doors_comboBox_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doors_comboBox_2ActionPerformed

    private void doors_comboBox_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doors_comboBox_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doors_comboBox_3ActionPerformed

    private void doors_comboBox_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doors_comboBox_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doors_comboBox_4ActionPerformed

    private void doors_comboBox_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doors_comboBox_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doors_comboBox_5ActionPerformed

    private void doors_comboBox_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doors_comboBox_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doors_comboBox_6ActionPerformed

    private void doors_comboBox_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doors_comboBox_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doors_comboBox_7ActionPerformed

    private void schedules_button_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedules_button_colorActionPerformed
        // Launch a Static JColorChooser with the current color set as default.
        //Updates the Color label to the selected color.
        Color color = JColorChooser.showDialog(MainWindow.this, 
                                              "Choose schedule, color:", 
                                              schedules_label_colorindicator.getBackground());
        schedules_label_colorindicator.setOpaque(true);
        
        if (color != null) {
            schedules_label_colorindicator.setBackground(color);
        }
    }//GEN-LAST:event_schedules_button_colorActionPerformed

    private void schedules_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schedules_tableMouseClicked
        //Method gets the selected row and uses the ro to get the name in colum 0.
        //The name is used to get the appropriate schedule from the schedules
        //HashMap. Schedules values will then be displayed in the schedule editor.
        
        DefaultTableModel dfm = (DefaultTableModel) schedules_table.getModel();
        
        int row = schedules_table.getSelectedRow();
        String name = (String) dfm.getValueAt(row, 0);
        
        Schedule schedule = schedules.get(name);
        
        String description = schedule.getDescription();
        Color color = schedule.getColor();
        ArrayList<DoorTime> times = schedule.getTimes();
        
        schedules_textfield_name.setText(name);
        schedules_textfield_description.setText(description);
        schedules_label_colorindicator.setBackground(color);
        schedules_label_colorindicator.setOpaque(true);
        
        setGroupEnabled(true, scheduleComponents);
    }//GEN-LAST:event_schedules_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashBoard_panel;
    private javax.swing.JButton doors_button_delete;
    private javax.swing.JButton doors_button_edit;
    private javax.swing.JButton doors_button_location;
    private javax.swing.JButton doors_button_new;
    private javax.swing.JButton doors_button_save;
    private javax.swing.JComboBox<String> doors_comboBox_1;
    private javax.swing.JComboBox<String> doors_comboBox_2;
    private javax.swing.JComboBox<String> doors_comboBox_3;
    private javax.swing.JComboBox<String> doors_comboBox_4;
    private javax.swing.JComboBox<String> doors_comboBox_5;
    private javax.swing.JComboBox<String> doors_comboBox_6;
    private javax.swing.JComboBox<String> doors_comboBox_7;
    private javax.swing.JLabel doors_label_building;
    private javax.swing.JLabel doors_label_doorName;
    private javax.swing.JLabel doors_label_friday;
    private javax.swing.JLabel doors_label_location;
    private javax.swing.JLabel doors_label_logs;
    private javax.swing.JLabel doors_label_monday;
    private javax.swing.JLabel doors_label_saturday;
    private javax.swing.JLabel doors_label_schedules;
    private javax.swing.JLabel doors_label_status;
    private javax.swing.JLabel doors_label_statusIndicatior;
    private javax.swing.JLabel doors_label_sunday;
    private javax.swing.JLabel doors_label_thursday;
    private javax.swing.JLabel doors_label_tuesday;
    private javax.swing.JLabel doors_label_wednesday;
    private javax.swing.JPanel doors_panel;
    private javax.swing.JPanel doors_panel_CRUD;
    private javax.swing.JPanel doors_panel_editor;
    private javax.swing.JRadioButton doors_radioButton_1;
    private javax.swing.JRadioButton doors_radioButton_2;
    private javax.swing.JRadioButton doors_radioButton_3;
    private javax.swing.JScrollPane doors_scrollpane_display;
    private javax.swing.JScrollPane doors_scrollpane_logs;
    private javax.swing.JTable doors_table_doors;
    private javax.swing.JTable doors_table_logs;
    private javax.swing.JTextField doors_textfield_doorname;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane mainWindow_tabbedPane;
    private javax.swing.JPanel schedules_CRUD_bottons;
    private javax.swing.JScrollPane schedules_ScrollPane_display;
    private javax.swing.JButton schedules_botton_add;
    private javax.swing.JButton schedules_botton_delete;
    private javax.swing.JButton schedules_botton_edit;
    private javax.swing.JButton schedules_botton_save;
    private javax.swing.JButton schedules_button_addtime;
    private javax.swing.JButton schedules_button_color;
    private javax.swing.JButton schedules_button_deletetime;
    private javax.swing.JButton schedules_button_edittime;
    private javax.swing.JLabel schedules_label_color;
    private javax.swing.JLabel schedules_label_colorindicator;
    private javax.swing.JLabel schedules_label_description;
    private javax.swing.JLabel schedules_label_name;
    private javax.swing.JLabel schedules_label_times;
    private javax.swing.JPanel schedules_panel;
    private javax.swing.JPanel schedules_panel_editor;
    private javax.swing.JScrollPane schedules_scrollpane_times;
    private javax.swing.JTable schedules_table;
    private javax.swing.JTable schedules_table_times;
    private javax.swing.JTextField schedules_textfield_description;
    private javax.swing.JTextField schedules_textfield_name;
    // End of variables declaration//GEN-END:variables


    private void writeModel(DoorManagerModel model) {
       // Writes the model as an object to disk
       
        try {
            
            FileOutputStream    fos = new FileOutputStream(new File("model.dms"));
            ObjectOutputStream  oos = new ObjectOutputStream(fos);
            
            oos.writeObject(model);
            oos.close();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }

    private DoorManagerModel readModel() {
        
        DoorManagerModel dmm = null;
        
        try {
            
            FileInputStream     fis = new FileInputStream(new File("model.dms"));
            ObjectInputStream   ois = new ObjectInputStream(fis);
            
            dmm = (DoorManagerModel)ois.readObject();
            fis.close();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return dmm;
    }

    private void buildschedulestables() 
    {
        
        
        String[] columnHeaders = {"Name", "Description", "Color", "Open Times"};
        Object[][] data = new Object[schedules.size()][4];
        
        int row = 0;
        for(String key : schedules.keySet()){
            
            Schedule schedule = schedules.get(key);
            
            data[row][0] = schedule.getName();
            data[row][1] = schedule.getDescription();
            
            Color color = schedule.getColor();
            data[row][2] = String.format("%d, %d, %d",color.getRed(), color.getGreen(), color.getBlue());
            
            data[row][3] = schedule.getTimes();
            row++;
            
            
        }
        
        DefaultTableModel dfm = new DefaultTableModel(data, columnHeaders);
        schedules_table.setModel(dfm);
    }

    private void buildScheduleGroup() {
        scheduleComponents[0] = schedules_botton_edit;
        scheduleComponents[1] = schedules_botton_delete;
        scheduleComponents[2] = schedules_botton_save;
        scheduleComponents[3] = schedules_textfield_name;
        scheduleComponents[4] = schedules_button_color;
        scheduleComponents[5] = schedules_textfield_description;
        scheduleComponents[6] = schedules_button_addtime;
        scheduleComponents[7] = schedules_button_edittime;
        scheduleComponents[8] = schedules_button_deletetime;
        scheduleComponents[9] = schedules_table_times;
    }

    private void buildDoorGroup() {
        
    }

    private void setGroupEnabled(boolean state, JComponent[] group) {
        
        for (JComponent component : group) 
        {
            component.setEnabled(state);
            
        }
    }

    private void DoorGroupEnabled(boolean b) {
        
    }
    
}
